name:                chapter22
version:             0.1.0.0
github:              "coacoas/chapter22"
license:             BSD3
author:              "Bill Carlson"
maintainer:          "bill@coacoas.net"
copyright:           "Copyright (c) 2018 Bill Carlson"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/coacoas/chapter22#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  chapter22-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chapter22
    - bytestring
    - hedis
    - mtl
    - network-uri
    - random
    - scotty
    - semigroups
    - text
    - transformers

tests:
  chapter22-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chapter22
