name:                chapter29
version:             0.1.0.0
github:              "coacoas/chapter29"
license:             BSD3
author:              "Bill Carlson"
maintainer:          "bill@coacoas.net"
copyright:           "Copyright (c) 2018 Bill Carlson"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/coacoas/chapter29#readme>

dependencies:
- base >= 4.7 && < 5
- random
- time
- text

library:
  source-dirs: src

executables:
  chapter29-exe:
    main:                Vignere.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chapter29

tests:
  chapter29-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chapter29
